"""create tables

Revision ID: 39f4ebb9db99
Revises: 
Create Date: 2023-11-13 04:53:44.920705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39f4ebb9db99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('record_id', sa.Integer(), nullable=False))
    op.drop_column('medical_records', 'id')
    op.add_column('patients', sa.Column('insurance', sa.String(length=100), nullable=False))
    op.add_column('patients', sa.Column('is_alive', sa.String(length=50), nullable=False))
    op.alter_column('patients', 'contact_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'contact_number',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_column('patients', 'is_alive')
    op.drop_column('patients', 'insurance')
    op.add_column('medical_records', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('medical_records', 'record_id')
    # ### end Alembic commands ###
